version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "20065:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - api_uploads:/app/uploads
    depends_on:
      - frontend
      - api
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: always

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["node", "dist/apps/api/apps/api/src/main.js"]
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/marketplace
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_S3_BUCKET=snapmarket-media
    depends_on:
      - mongo
      - redis
    volumes:
      - api_uploads:/app/uploads
    restart: always

  workers:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["node", "dist/apps/workers/apps/workers/src/main.js"]
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/marketplace
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:alpine
    restart: always

volumes:
  mongo_data:
  api_uploads:
